services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: true

     # security: restriction uri parser
    MembersBundle\Security\RestrictionUri: ~

     # security: restriction query parser
    MembersBundle\Security\RestrictionQuery: ~

    MembersBundle\Security\UserChecker: ~

    MembersBundle\Security\UserProvider: ~

    MembersBundle\Security\EmailUserProvider: ~

    MembersBundle\Security\Encoder\Factory\UserAwareEncoderFactory:
        arguments:
            $className: 'Pimcore\Security\Encoder\PasswordFieldEncoder'
            $arguments: ['password']

    MembersBundle\Security\LuceneSearchAuthenticator: ~